### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by RichardLitt** [nolanlawson/open-source#2]
> Nobody opens an issue or a pull request when they’re satisfied with your work.

Found a repo that wasn't all that maintained so I didn't ping 10k people. Thanks for the work you do. That's all. :)

**Comment by nolanlawson** [comment]
Heh thanks, this made me chuckle. :) I had forgotten this repo existed. Think I set it up as a personal todo list, but gave up at some point.

**Comment by RichardLitt** [comment]
I've got one of those. I keep it private. It works pretty well for keeping an eye on what all of my larger projects are. It works really well with the Projects board.

There's also this, https://github.com/RichardLitt/todo, but no one really uses that. 

Glad I made you chuckle. \o/!
